### ISSUE TITLE
add league save and get methods

### ISSUE THREAD

**Issue by shlimp** [shlimp/betwithamigos#1]
add league.save and league.get methods

league.save(id=Number, party_id=Number)
if party_id isn't passed, make it public, otherwise make it private and associate with the party

league.get(id=Number, party_id=Number)
if party_id isn't passed get all public and all user leagues, else get just party leagues

**Comment by BetWithFriend** [comment]
ניסיתי, אבל לצערי זה כל מה שיצא, נראה לי שבכל מקרה, נשב על זה מחר או בסופש מתישהו.@classmethoddef save(id=Number, party_id=Number): if party_id is None: party_id.leagues.type=LeagueTypeEnum.PUBLIC party_id.leagues.type=LeagueTypeEnum.PRIVATE @classmethod def get(id=Number, party_id=Number): if party_id is None: return League.type == LeagueTypeEnum.PUBLIC return League.get(id, party_id) 

     On Wednesday, February 11, 2015 8:36 AM, shlimp <notifications@github.com> wrote:
   

 add league.save and league.get methodsleague.save(id=Number, party_id=Number)
if party_id isn't passed, make it public, otherwise make it private and associate with the partyleague.get(id=Number, party_id=Number)
if party_id isn't passed get all public and all user leagues, else get just party leagues—

**Comment by BetWithFriend** [comment]
לצערי לא ממש הצלחתי.

אשמח אם נוכל לשבת על זה השבוע, ולאט לאט נבנה את זה ביחד.
זה מה שיצא לי בינתיים:

from flask import Blueprint
from betwithamigos import BetWithAmigos
from leagues.models import League, Team
from const import LeagueTypeEnum

jsonrpc = BetWithAmigos.get_rpc()
db = BetWithAmigos.get_db()

bp = Blueprint('leagues', __name__)
jsonrpc.register_blueprint(bp)

@jsonrpc.method_save('league.save(id=Number,party_id=Number)', model=League)
def league_save(user, obj):
    if not obj.party_id:
        obj.type = LeagueTypeEnum.PUBLIC
    else:
        obj.type = LeagueTypeEnum.PRIVATE
        obj.owner = user

        db.session.add(obj)
        db.session.commit()
        return obj.asdict()


@jsonrpc.method_get('league.get(id=Number, party_id=Number)', model=League)
def league_get(user, qs):
    if not obj.id:
        result = []
